[package]
name = "definitely_hyped"
version = "0.1.0"
authors = ["Andrew Crites <acjrites@gmail.com>"]

[dependencies]
json = "0.11.13"
rusoto_core = "0.36.0"
rusoto_s3 = "0.36.0"
futures = "0.1.25"
reqwest = "0.9.5"
